import { useRouter } from 'next/router';
import useSWR from 'swr';
import { fetcher } from '@/utils/fetcher';
import { useEffect, useState } from 'react';
import Tag from '@/components/Tag';
import { v4 as uuidv4 } from 'uuid';
import Cta from '@/components/Cta';
import { Splide, SplideSlide, SplideTrack } from '@splidejs/react-splide';
import '@splidejs/react-splide/css/core';
import Controls from '@/components/slider/Controls';
import Image from 'next/image';
import Head from 'next/head';

export default function Project() {
  const router = useRouter();
  const slug = router.query.slug;
  const { data } = useSWR('/api/projects', fetcher);
  const [project, setProject] = useState(null);
  const [labels, setLabels] = useState(null);
  const locale = router.locale ? router.locale : router.defaultLocale;

  useEffect(() => {
    if (!data || !slug) return;

    setLabels(data.labels);
    const current = data.projects?.find((elem) => elem.slug === slug);

    if (typeof current !== 'undefined') {
      setProject(current);
    } else {
      router.push('/not-found');
    }
  }, [data, slug]);

  return (
    <>
      {project ? (
        <>
          <Head>
            <title>{locale === 'fr' ? 'Projet' : 'Project'} - {project.title[locale]}</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          
          <div className='container mx-auto mt-12 md:mt-16 px-5 top-background'>
            <div className='flex flex-col md:flex-row-reverse md:justify-end mb-24 md:mb-32'>
              
              <div className='md:w-1/2 md:pl-4 lg:pl-[8.3333%] md:mt-10 lg:mt-16'>
                <h1 id='project-title' className='font-serif text-deep-green text-2xl md:text-3xl'>{project.title[locale]}</h1>
                <div className='mt-7 md:mt-9'>
                  {project.clientName ? (
                    <p className='mt-2'>{labels.clientName[locale]}: {project.clientName[locale]}</p>
                  ) : null}
                  {project.author ? (
                    <p className='mt-2'>{labels.author[locale]}: {project.author}</p>
                  ) : null}
                  {project.work ? (
                    <p className='mt-2'>{labels.work[locale]}: {project.work[locale]}</p>
                  ) : null}
                </div>
                <p className='mt-7 lg:mt-10'>{project.description[locale]}</p>
                <div className='mt-7 lg:mt-10'>
                  {project.tags?.map((tag) => <Tag key={uuidv4()} label={tag} />)}
                </div>
              </div>

              <div className='mt-9 md:mt-0 md:w-1/2 lg:w-5/12'>
                <div>
                  <Splide
                    hasTrack={false}
                    aria-labelledby='project-title'
                  >
                    <SplideTrack>
                      {project.images.map((image) => (
                        <SplideSlide key={uuidv4()}>
                          <div className='relative w-full aspect-[600/382] rounded-lg overflow-hidden'>
                            <Image src={image.url} alt={image.description[locale]} width='600' height='382' className='w-full h-full object-cover' />
                          </div>
                        </SplideSlide>
                      ))}
                    </SplideTrack>
                    <Controls />
                  </Splide>
                </div>
                <div className='text-center mt-8'>
                  {project.website ? (
                    <Cta href={project.website} target='_blank' rel='noopener noreferrer'>{labels.website[locale]}</Cta>
                  ) : null}
                </div>
              </div>

            </div>
          </div>
        </>
      ) : null}
    </>
  );
}
