import Head from 'next/head';
import Hero from '@/components/homepage/Hero';
import Introduction from '@/components/homepage/Introduction';
import Knowledge from '@/components/homepage/Knowledge';
import Projects from '@/components/homepage/Projects';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pierre Andreski - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Hero />
        <Introduction />
        <Knowledge />
        <Projects />
      </main>
    </>
  )
}
