import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pierre Andreski - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1 className='text-lg font-bold underline font-serif'>Homepage</h1>
        <p>Lorem ipsum</p>
      </main>
    </>
  )
}
